// Generated by CoffeeScript 1.9.3
(function() {
  var _, ask, prepareText, questionnaire, readLine;

  readLine = require('readline-sync');

  _ = require('underscore');

  prepareText = function(options) {
    return _.map(options, function(option, ind) {
      return "(" + (ind + 1) + ") " + option;
    }).join(" or ") + '?';
  };

  ask = function(q) {
    var answer, i, selected, text;
    text = q.text || prepareText(q.options);
    text = text + " ";
    answer = readLine.question(text);
    i = parseInt(answer, 10);
    selected = q.options[i - 1];
    if (!selected) {
      console.log("Unsupported answer: please enter a number from 1 to " + q.options.length);
      return ask(q);
    }
    return [q.id, selected];
  };

  questionnaire = function(questions) {
    return _.chain(questions).map(ask).object().value();
  };

  module.exports = questionnaire;

}).call(this);
