// Generated by CoffeeScript 1.9.3
(function() {
  var _, ask, questionnaire, readLine;

  readLine = require('readline-sync');

  _ = require('underscore');

  ask = function(id, options) {
    var answer, i, out, text;
    text = _.map(options, function(option, ind) {
      return "(" + (ind + 1) + ") " + option;
    }).join(" or ") + '? ';
    answer = readLine.question(text);
    i = parseInt(answer, 10);
    out = options[i - 1];
    if (!out) {
      console.log('Unsupported answer');
      return ask(id, options);
    }
    return [id, out];
  };

  questionnaire = function(questions) {
    var answers;
    answers = questions.map(function(q) {
      return ask(q.id, q.options);
    });
    return _.object(answers);
  };

  module.exports = questionnaire;

}).call(this);
